[package]
name = "lenna-cli"
version = "0.1.0"
authors = ["Christian <chriamue@gmail.com>"]
edition = "2018"

[lib]
name = "lenna_cli"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "lenna-cli"
path = "src/bin/bin.rs"

[dependencies]
libloading = "0.5"
structopt = "0.3.13"
lenna_core = {git = "https://github.com/lenna-project/lenna-core", branch="main" }
image = { version = "0.23.12", default-features = false, features = ["png"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
