name: lenna-cli
version: git
summary: This is the Command Line Interface for Lenna.
description: |
  lenna-cli is a command line program for converting images.
confinement: devmode
base: core20
license: MIT

parts:
  lenna-cli:
    plugin: rust
    source: .
    rust-features:
      - libloading

  lenna-plugins:
    plugin: rust
    source: https://github.com/lenna-project/lenna-plugins.git
    override-build: |
       cargo build --all --release
       mkdir $SNAPCRAFT_PART_INSTALL/plugins
       cp target/release/lib*.so $SNAPCRAFT_PART_INSTALL/plugins/

apps:
  lenna-cli:
    command: bin/lenna-cli
    plugs: [home, removable-media]
    environment:
      LENNA_PLUGINS: $SNAP/plugins
